### ISSUE TITLE
No matching conversion for functional-style cast from 'const juce::File' to 'zero::File'

### ISSUE THREAD

**Issue by wwerk** [acendan/zerochecker#2]
Hi, I am trying to build on Apple Silicon and I am getting a following error:

```
~/GitHub/zerochecker/Source/console.cpp:37:39: No matching conversion for functional-style cast from 'const juce::File' to 'zero::File'
~/GitHub/zerochecker/Source/console.cpp:42:38: No matching conversion for functional-style cast from 'juce::File' to 'zero::File'
```

If I am correct, it would seem that the `zero::File` struct does not have a constructor necessary for this casting, as it only has a default one?
Funnily enough, with those lines changed so the argument is removed, it builds:
```
m_zerochecker.m_files.push_back(zero::File());
```

**Comment by acendan** [comment]
Hi wwerk! Thanks for pointing that out. I actually noticed the same warning from clang tidy while compiling the Linux build last night. 

Unfortunately, with the default constructor and no arguments, the tool won't really do anything. Did you test if after compiling? 

Curiously I didn't get any warnings whatsoever on VS2022 (MSVC).

**Comment by wwerk** [comment]
Adding a constructor that takes in a `const juce::File file` argument fixed the issue, opened a PR for that.
